export default function About(){
    return(
        <div className="about  max-w-7xl mx-auto px-4 py-8">
            <h1 className="p-heading animation text-3xl md:text-4xl font-bold text-center mb-8">About Us</h1>
            <p className="p-content text-lg leading-relaxed text-justify md:text-xl md:leading-relaxed">
            Welcome to our blog, a vibrant celebration of the rich tapestry of Pakistani culture! Here, we delve into the heart and soul of Pakistan through its colorful festivals, exquisite fashion, mouthwatering cuisine, soulful music, inspiring art, and unique traditions. Our mission is to showcase the beauty and diversity of Pakistani heritage, inviting you to experience the energy of its festivals, the elegance of its fashion, the richness of its flavors, and the creativity of its artists. Whether you're a local or exploring our culture from afar, we aim to create an engaging and informative space that fosters appreciation and understanding of Pakistan's timeless traditions and modern expressions. Join us on this journey of discovery and celebration! a vibrant celebration of the rich tapestry of Pakistani culture! Here, we delve into the heart and soul of Pakistan through its colorful festivals, exquisite fashion, mouthwatering cuisine, soulful music, inspiring art, and unique traditions. Our mission is to showcase the beauty and diversity of Pakistani heritage, inviting you to experience the energy of its festivals, the elegance of its fashion, the richness of its flavors, and the creativity of its artists. Whether you're a local or exploring our culture from afar, we aim to create an engaging and informative space that fosters appreciation and understanding of Pakistan's timeless traditions and modern expressions. Join us on this journey of discovery and celebration!a vibrant celebration of the rich tapestry of Pakistani culture! Here, we delve into the heart and soul of Pakistan through its colorful festivals, exquisite fashion, mouthwatering cuisine, soulful music, inspiring art, and unique traditions. Our mission is to showcase the beauty and diversity of Pakistani heritage, inviting you to experience the energy of its festivals, the elegance of its fashion, the richness of its flavors, and the creativity of its artists. Whether you're a local or exploring our culture from afar, we aim to create an engaging and informative space that fosters appreciation and understanding of Pakistan's timeless traditions and modern expressions. Join us on this journey of discovery and celebration!
            </p>
        </div>
    )
}